
package eu.datex2.schema._3.common;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FaultSeverityEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="FaultSeverityEnum"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="low"/&gt;
 *     &lt;enumeration value="medium"/&gt;
 *     &lt;enumeration value="high"/&gt;
 *     &lt;enumeration value="unknown"/&gt;
 *     &lt;enumeration value="_extended"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "FaultSeverityEnum")
@XmlEnum
public enum FaultSeverityEnum2 {


    /**
     * The fault is of low severity and has only limited impact on the usability of the
     *             equipment or the value of the data generated by the equipment.
     *           
     * 
     */
    @XmlEnumValue("low")
    LOW("low"),

    /**
     * The fault is of medium severity which will significantly limit the usability of
     *             the equipment or devalue the usefulness of the data generated by the equipment.
     *           
     * 
     */
    @XmlEnumValue("medium")
    MEDIUM("medium"),

    /**
     * The fault is of high severity which will render the equipment unusable or any data
     *             generated by the equipment to be of no value.
     *           
     * 
     */
    @XmlEnumValue("high")
    HIGH("high"),

    /**
     * The fault is of unknown severity and hence its effect on the usability of the
     *             equipment or the usefulness of the data generated by the equipment can not be assessed.
     *           
     * 
     */
    @XmlEnumValue("unknown")
    UNKNOWN("unknown"),
    @XmlEnumValue("_extended")
    EXTENDED("_extended");
    private final String value;

    FaultSeverityEnum2(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static FaultSeverityEnum2 fromValue(String v) {
        for (FaultSeverityEnum2 c: FaultSeverityEnum2 .values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
