name: Build and test on PR

on:
  pull_request:
    paths:
      - "**/*.kts"
      - "**/*.kt"
      - "**/*.java"
      - "**/*.gradle"

jobs:
  find-module-changes:
    name: Find module changes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Find modules with changes
        id: find-module-changes
        uses: svvsaga/github-actions-public/find-gradle-module-changes@v20.0.0
        with:
          token: ${{ github.token }}
    outputs:
      matrix: ${{ steps.find-module-changes.outputs.matrix }}
      has_results: ${{ steps.find-module-changes.outputs.has_results }}

  build-and-test:
    name: Build and test
    runs-on: ubuntu-latest
    if: needs.find-module-changes.outputs.has_results == 'true'
    needs: find-module-changes
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.find-module-changes.outputs.matrix) }}
    defaults:
      run:
        working-directory: ${{ matrix.path }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Gradle build and test
        run: ./gradlew test
