name: Run all integration tests nightly

on:
  schedule:
    - cron: '37 2 * * *' # 02:37 every night
  workflow_dispatch:

jobs:
  run-all-gradle-integration-tests-and-report-to-slack:
    name: Run all Gradle integration tests and report errors to Slack channel
    uses: svvsaga/github-actions-public/.github/workflows/run-all-gradle-integration-tests-and-report-to-slack.yml@v7.1.0
    with:
      ignore_modules: "./example,./plugins/saga-build"
    secrets:
      slack_webhook_url: ${{ secrets.SLACK_INTEGRATION_TEST_FAILED_YGGDRASIL_WEBHOOK_URL }}
